import Head from 'next/head'
import Image from 'next/image'
import { Montserrat, Noto_Sans_SC } from 'next/font/google'
import { FC, PropsWithChildren, useEffect, useState } from 'react'
import useAuth from '@/stores/useAuth'
import { useRouter } from 'next/router'
import Loading from '@/components/Loading'
import styled from 'styled-components'
import { AnimatePresence, motion } from 'framer-motion'
import Link from 'next/link'
import {
  PiChartLineUp,
  PiHouse,
  PiMaskHappyDuotone,
  PiToteSimple,
  PiTrolleyDuotone,
  PiUserCircleDuotone,
  PiUsersDuotone,
} from 'react-icons/pi'

const montserrat = Montserrat({ subsets: ['latin'] })
const noto_sc = Noto_Sans_SC({ weight: '900', subsets: ['latin'] })

const Navbar = styled(motion.div)`
  padding: 1rem;
  background-color: white;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  border-bottom: 1px solid #737373; /* border-neutral-500 */
  display: flex;
  justify-content: space-between;
`

const LeftNav = styled.div`
  display: flex;
  gap: 0.5rem; /* Tailwind's gap-2 */
  align-items: center;
`

const RightNav = styled.div`
  display: flex;
  align-items: center;
  flex-shrink: 0;
`

const LogoNav = styled.div`
  flex-shrink: 0;
  width: 100px;
  position: relative;
  font-size: 24px;
`

const LinksZone = styled.div`
  display: flex;
  align-items: center;
  gap: 0.5rem; /* Tailwind's gap-2 */
  font-size: 12px;
`

const StyledLink = styled(Link)`
  display: flex;
  align-items: center;
  gap: 0.2rem;
  text-decoration: none;
  color: black;
  &:hover {
    color: #737373;
  }
`

const Layout: FC<PropsWithChildren> = ({ children }) => {
  const auth = useAuth()
  const router = useRouter()
  const [ready, setReady] = useState(false)

  const handleLogout = () => {
    auth.clearToken()
  }

  useEffect(() => {
    if (!auth.validate()) {
      router.replace('/login')
    } else {
      setReady(true)
    }
  }, [auth.token])

  if (!ready) return <Loading />

  if (ready)
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={montserrat.className}>
          <AnimatePresence>
            <Navbar
              initial={{ opacity: 0, y: -50 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -50 }}
              transition={{ duration: 0.5 }}
            >
              <LeftNav>
                <LogoNav className={noto_sc.className}>诺米波</LogoNav>
                <LinksZone>
                  <StyledLink href={'/'}>
                    <PiHouse /> Dashboard
                  </StyledLink>
                  <span>|</span>
                  <StyledLink href={'/products'}>
                    <PiTrolleyDuotone /> Products
                  </StyledLink>
                  <StyledLink href={'/orders'}>
                    <PiToteSimple /> Orders
                  </StyledLink>
                  <StyledLink href={'/transactions'}>
                    <PiChartLineUp /> Transactions
                  </StyledLink>
                  <span>|</span>
                  <StyledLink href={'/users'}>
                    <PiUsersDuotone /> Users
                  </StyledLink>
                  <StyledLink href={'/roles'}>
                    <PiMaskHappyDuotone /> Roles
                  </StyledLink>
                </LinksZone>
              </LeftNav>
              <RightNav>
                <PiUserCircleDuotone style={{ fontSize: 28, cursor: 'pointer' }} onClick={() => handleLogout()} />
              </RightNav>
            </Navbar>
          </AnimatePresence>
          <div style={{ padding: 8, paddingTop: 12 }}>{children}</div>
        </main>
      </>
    )
}

export default Layout
